destination: ./public
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - bin
  - config.ru
  - public
  - renovate.json
  - tmp
  - vendor
sitemap:
  url: http://andre.arko.net
future: false
