name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  push_drafts:
    if: github.repository == 'indirect/andre.arko.net'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:indirect/drafts.arko.net.git
          ssh_private_key:
            ${{ secrets.DRAFTS_SSH_DEPLOY_KEY }}
    
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_ENVIRONMENT: ${{ vars.HUGO_ENVIRONMENT || 'production' }}
    steps:
      - uses: actions/checkout@v4
      - name: Read Hugo version
        id: hugo-version
        run: echo "HUGO_VERSION=$(cut -b 2-99 .hvm)" >> "$GITHUB_OUTPUT"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ steps.hugo-version.outputs.HUGO_VERSION }}
      - name: Run Hugo
        run: bin/build ${{ vars.HUGO_BASEURL }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
